version: '2'

services:
  vpn_proxy:
    image: mgering/openvpn-proxy
    build: openvpn
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /home/mgering/openvpn:/vol/config
    privileged: true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "1080:1080"
